### PR TITLE
refactor(css): buttons-core merge .vaadin-button-container styles

### PR DESCRIPTION
**Pull request by paulkirspuu**

### CODE REVIEW

**Comment by lkraav** [comment]
Before/After screenshot?

This is a core Vaadin style change. Can you evaluate why vaadin-button works with it? It's probably to do with it having an inner container as well, and we should figure out how to "translate" it for native button.. Maybe this PR is exactly what's needed, but can you bring details?

See also https://github.com/vaadin/web-components/blob/23.3/packages/button/theme/lumo/vaadin-button-styles.js

**Comment by paulkirspuu** [comment]
> Before/After screenshot?
> 
> This is a core Vaadin style change. Can you evaluate why vaadin-button works with it? It's probably to do with it having an inner container as well, and we should figure out how to "translate" it for native button.. Maybe this PR is exactly what's needed, but can you bring details?
> 
> See also https://github.com/vaadin/web-components/blob/23.3/packages/button/theme/lumo/vaadin-button-styles.js


before:

image

image

after:

image

image

**Comment by paulkirspuu** [comment]
> This is a core Vaadin style change. Can you evaluate why vaadin-button works with it? It's probably to do with it having an inner container as well, and we should figure out how to "translate" it for native button.. Maybe this PR is exactly what's needed, but can you bring details?

Vaadin inner container controls the centering, indeed. So if we were to bring over styles from `.vaadin-button-container`, we'd have similar result to vaadin button.

So perhaps this is the way forward, instead of editing padding value.

cc @pawelkmpt

**Comment by lkraav** [comment]
> Vaadin inner container controls the centering, indeed. So if we were to bring over styles from `.vaadin-button-container`, we'd have similar result to vaadin button.
> 
> So perhaps this is the way forward, instead of editing padding value.

Be specific, what is "this"?

I'll assume "bring over styles from `.vaadin-button-container`": yes, exactly - and I think we would just try to merge them into singular `.button` here.

Can you give this a shot?

**Review by lkraav — APPROVED** [review]
Looks simple and promising.

Are you any less than 100% confident in this, do I have to go hands on to check?

**Comment by paulkirspuu** [comment]
> Looks simple and promising.
> 
> Are you any less than 100% confident in this, do I have to go hands on to check?

I'm confident. My local staging does not mimic 100% live site, but from what I do have, I'd say it works.

**Pull request merged**
